<a href="https://colab.research.google.com/github/sanchitsetia/mathematics_for_ml/blob/main/Session_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
v = np.array([1,2,1])
w = np.array([2,3,4])

In [4]:
# vector addition
v_sum = v+w
print(v_sum)

[3 5 5]


In [5]:
# vector subtraction
v_sub = v-w
print(v_sub)

[-1 -1 -3]


In [6]:
# scalar multiplication
print(2*v)

[2 4 2]


In [7]:
# dot product
dot = np.dot(v,w)
print(dot)

12


In [8]:
# length of vector
length = np.linalg.norm(v)
print(length)

2.449489742783178
